stages:
  - build
  - deploy

build:
  stage: build
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build --prod --aot
  cache:
    paths:
      - ./node_modules
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/bookshelves
  only:
    - master

deploy:
  stage: deploy
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -yqq ruby ruby-dev nodejs --silent
    - gem install dpl
    - dpl --provider=heroku --app=bookshelves --api-key=$HEROKU_API_KEY --skip_cleanup=true
  dependencies:
    - build
  only:
    - master
